### ISSUE TITLE
Can I merge this plugin into the app?

### ISSUE THREAD

**Issue by craftzdog** [q1701/inkdrop-import-markdown#2]
Hi👋

Thank you so much for making this plugin!
As I'm getting the same request many times that people want to import .md files, I decided to support importing markdown files by default, without needing to install the plugin.
I found that your code looks so great and I would like to reuse them.
Can I create a repository based on yours?

Thanks!

**Comment by q1701** [comment]
Sure! I hope this code helps you.

**Comment by craftzdog** [comment]
Thank you! 😄
